#define HOEHE 30
#define BREITE 50
#define ANZ_FUTTERSTUECKE 10
#define ANZ_VERTIKALE_WAENDE 10
#define ANZ_HORIZONTALE_WAENDE 5
#define ANZ_DIAGONALE_WAENDE 5
#define WAND_LAENGE 6
#define START_BEREICH_SEITENLAENGE 13

#define MAX_SCHLAENGE_LAENGE 100
#define START_SCHLANGEN_LAENGE 5


#define FELD_LEER ' '
#define FELD_WAND '#'
#define FELD_FUTTER 'o'
#define FELD_SCHLANGE_KOPF '@'
#define FELD_SCHLANGEN_STUECK '+'

